version: "3"
services:

  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
    networks:
      - net

  dolibarr:
          # build: .
    image: mazzyst/dolibarr
    ports:
      - "80:80"
    depends_on:
      - "db"
    networks:
      - net
networks:
    net:
