version: "3"
services:

  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - net

  dolibarr:
    build: .
    ports:
      - "80:80"
    depends_on:
      - "db"
    networks:
      - net
networks:
    net:
